plugins {
    id 'org.springframework.boot' // 부모의 버전을 따라감
    // dependency-management는 부모 subprojects에서 이미 apply됨
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

//    implementation 'org.springframework.boot:spring-boot-starter'

    // @RestController, @RequestMapping 등을 쓰기 위해 반드시 필요!
    // 'org.springframework.boot:spring-boot-starter'의 확장판
    implementation 'org.springframework.boot:spring-boot-starter-web'
}

bootJar { enabled = true }
jar { enabled = false }