dependencies {
    //web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    //jpa
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    //web socket
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    //DB
    runtimeOnly 'com.mysql:mysql-connector-j'
    testRuntimeOnly 'com.h2database:h2'


    //모듈 간 의존성
    implementation project(':common')
    implementation project(':module_security')
}

bootJar{ enabled = true }
jar{ enabled = false }

