server:
  port: 8081

spring:
  application:
    name: plab


  profiles:
    include: feign,redis,kafka #coomon 모듈에 있는 redis,feign 같이 읽어옴

  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/hospital_visit_service?&serverTimezone=Asia/Seoul
    username: root
    password: 385tjdgus
  #    url: ${MYSQL_URL}
  #    username: ${MYSQL_USERNAME}
  #    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      #      ddl-auto: create-drop #애플리케이션 시작 시 기존 스키마 삭제 후 생성,애플리케이션 종료 시 스키마 삭제
#      ddl-auto: create # 애플리케이션 시작 시 기존 스키마 삭제 후 생성, 애플리케이션 종료 시 스키마 삭제 X(데이터 남아있음)
      ddl-auto: none # 애플리케이션 시작 시 기존 스키마 삭제 후 생성, 애플리케이션 종료 시 스키마 삭제 X(데이터 남아있음)
      database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    # 1. 💡 [핵심] 스프링 트랜잭션 매니저의 실제 참여/보류/생성 상세 로그 활성화
#    org.springframework.transaction.support.AbstractPlatformTransactionManager: DEBUG
    org.springframework.transaction: DEBUG

    # 2. 스프링 핵심 트랜잭션 인터셉터 (현재 설정 유지 혹은 생략 가능)
    org.springframework.transaction.interceptor: TRACE

    # 3. 하이버네이트(JPA) 트랜잭션 로그
    org.hibernate.orm.tx: DEBUG