dependencies {
    //mail
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    //
    implementation 'org.springframework:spring-context'

    //web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    //jpa
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // kafka
    implementation 'org.springframework.kafka:spring-kafka' // kafka 의존성 추가

    //DB
    runtimeOnly 'com.mysql:mysql-connector-j'
    testRuntimeOnly 'com.h2database:h2'

    //===========test=============//
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.google.code.gson:gson:2.8.9'

    implementation project(':common')
}

bootJar{ enabled = true }
jar{ enabled = true }
