dependencies {
    //api
    // 유효성 검증에 필요한 모든 핵심 라이브러리(spring-coantext 포함)가 들어있습니다.
    api 'org.springframework.boot:spring-boot-starter-validation'

//    implementation 'org.springframework:spring-web'
    //1. Spring Web 관련 예외 클래스 참조용
    compileOnly 'org.springframework:spring-webmvc'
    //2. Servlet 관련 클래스(ServletException 등) 참조용 (추가!)
    compileOnly 'jakarta.servlet:jakarta.servlet-api'

    //redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    implementation 'com.fasterxml.jackson.core:jackson-databind'

    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.15.2'// for JsonInclude

    //aop
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    //openfeign
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'


    //test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

}

bootJar{ enabled = false }
jar{ enabled = true }