spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: sunghyun7895@naver.com
    password: R2Y89XG1D5DB
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false