spring:
  application:
    name: batch

  main:
    web-application-type: none

  profiles:
    include: feign,redis,mail,kafka

  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital_visit_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 385tjdgus
#    url: ${MYSQL_URL}
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}

  batch:
    job:
      enabled: false


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    type-handlers-package: com.sunghyun.batch.infrastructure.typehandler





